### ISSUE TITLE
File-less interface

### ISSUE THREAD

**Issue by hcarty** [mirage/ocaml-tar#36]
It would be useful to have a string/bytes/buffer/cstruct-backed module included to interact with tar files in flight.

If there's interest I could write and contribute something but it would likely be a month or more before I have time to do so.

**Comment by copy** [comment]
This would also be useful for me. I'm wondering, since `Tar` is functorized over a generic `IO` module, it would make more sense to provide `IO` for strings in a separate project so it can be used in all mirage projects that use such an `IO` signature. Maybe it already exists (I briefly looked and couldn't find it).

**Comment by hcarty** [comment]
I'm working on something simple using `Cstruct.t` as the source for reading.  I don't need writing at the moment but if I have time to do so I'll add both and submit a PR.

**Comment by samoht** [comment]
sorry to not have answered before, but yes a file-less interface makes a lot of sense. Would be great to have a non-blocking streaming codec as well (where you can control memory allocations).

**Comment by hcarty** [comment]
#54 provides a relatively simple approach.  There are a number of ways to make it more efficient but that approach is at least minimally invasive.

**Comment by hannesm** [comment]
@hcarty since #54 is merged and released now, should we (you!) close this issue?

**Comment by hcarty** [comment]
Definitely!  Thank you for the reminder @hannesm
